cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode10
      script:
        - swift build
        - swift run package-config-example --verbose
        
    - os: osx
      osx_image: xcode11
      script:
        - swift build
        - swift run package-config-example --verbose

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
      script:
        - swift build
        - swift run package-config-example --verbose
